# basic options 
title: Your awesome title 
author:Github User 
email: your-email@domai.com
description: A wonderful site 
twitter username:jekyllrb
github usernam: jekerll

# Build settings
remote_theme: jekyll/minima

